name: PR Comment Test

on:
  issue_comment:
    types: [created]

jobs:
  run-on-pr-comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, 'test-trigger') }}
    steps:
      - name: Show PR comment
        run: echo "Triggered by PR comment: ${{ github.event.comment.body }}"
